### ISSUE TITLE
How do we build an app from the Single APK approach 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#113]
For the Single APK approach, assuming we would want to produce an app for the different clients/products that we are building i.e. G6PD, mADX, Covax, ANC. Do we either 
- [ ] Have a single code repo with multiple code branches that will reproduce  the different applications 
- [ ] Have multiple repositories for different  projects 
- [ ] Have  the configuration for the product flavours synced from the  build Gradle e.g https://github.com/opensrp/opensrp-client-chw/blob/master/opensrp-chw/build.gradle
- [x] Have Server side config synced and loaded to the app upon login and generate the different UI/Workflows  
cc. @pld

**Comment by pld** [comment]
The last option, single apk, single app -- configs determine the product

**Comment by f-odhiambo** [comment]
**Some notes here:**
1. The base app should be a skeleton that will be receiving configs synced from the HAPI FHIR server? (Could be the Workflow server API on SDK )r that will be used to reproduce the different workflows for a specific use case e.g. ANC
2. What does the base app contain?
Configurable 
- Login/Logout 
- Register 
- Patient list
- Patient profile
- Sync
3. What will be the structure of the configuration and the sync mechanism to load them to the application?
4. What functionality will be needed to be built to be able to perform a configuration task?

**Comment by pld** [comment]
For (3) the immediate option I see is tying these to the users role and syncing on login. If I'm a user with a covax role on first login it syncs down the fhir configurations for the roles I'm assigned, so the vax user profile view, the vax list view -- then it syncs the patients in my catchment area.

I feel pretty strongly we should push ALL configuration into FHIR files so that we can use it for syncing, including feature flags. I don't see the benefit of a separate configuration method that requires us to do another sync. If this means we have to use resources in unintended ways, like serialize a config, load it into a library resource and deserialize it on download, that is fine, we can built custom/unballoted resources overtime to move towards standard for all this later.

**Comment by ndegwamartin** [comment]
@pld @f-odhiambo i've enabled [Discussions](https://github.com/opensrp/fhircore/discussions) for fhir core. We can explore using it for discussions and only create Github issues when we have tasks. Let me know what you think

**Comment by ndegwamartin** [comment]
And **P.S.** discussions can be converted to issues

**Comment by ndegwamartin** [comment]
**P.S.** discussions can be converted to issues and vice versa
