### ISSUE TITLE
[Quest] Update the current scheduling and tasking to use a PlanDefinition 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1255]
**Description of feature**
- $Lite currently uses the StructureMap to create the CarePlans and Tasks for different Visits
- We would want to update the functionality to now generate the CarePlan & Tasks from a defined PalnDefinition

**Describe the enhancement**
- [ ] Write a StructureMap to generate a CarePlan & Task for a PlanDefition.
     - [x] We can use the following PlanDefition as a sample ~ Child routine visit [PlanDefinition](https://github.com/opensrp/fhir-resources/blob/main/ecbis/plan_definition/child_routine_visit.json).
     - [x] Update every other PlanDefinition Actitivty to add the StructureMap to be used for it's extraction. 
- [ ] The PlanDefinition Activity should only be excuted when the condition expression evaluates to true. 
     - [x] Here is a sample [condition expression](https://github.com/opensrp/fhir-resources/blob/ddc1d704989c2616c2a44f3d0a5f2bee2f529f2e/ecbis/plan_definition/child_routine_visit.json#L67).

**Acceptance criteria**
- [x] All $lite executions should require a PlanDefition to work. 
- [x] All PlanDefitions should have a condition expression. 
- [x] All PlanDefitions should have a StructureMap attached to them.

**Comment by maimoonak** [comment]
@dubdabasoduba @pld @f-odhiambo The trigger definition action type suggests some of the events happening into system. So what here we are doing is, whenever a form is submitted (QuestionnaireViewModel), we check if it entity creation (type=data-added), then evaluate the condition with data that was submitted. And if condition is true we run the plan definition and the flow to generate the tasks

**Comment by dubdabasoduba** [comment]
@maimoonak The event types I am looking at are as follows. 

1. Identify from the system side where a specific PlanDefinition is to be used and what determines its use. 
2. Idenifty from the PlanDefinition `action` on when the conditions are correct for the action to be executed and the CarePlan and Tasks to be generated.

**Comment by maimoonak** [comment]
Done in PR above. Some deviations and points @pld @dubdabasoduba @f-odhiambo 

[PlanDefinition](https://github.com/opensrp/fhircore/blob/7b0542c75fde526e30966dac35925bbae370bb7f/android/engine/src/test/resources/plans/child-routine-visit/plandefinition.json) : 
- action.trigger is not suitable as it has as [different purpose](https://hl7.org/fhir/metadatatypes.html#TriggerDefinition). alternate of it is [action.condition](https://hl7.org/fhir/plandefinition-definitions.html#PlanDefinition.action.condition) which with kind.applicability serves the purpose of validating the plan.action validity
- action.definition should be activity-definition (although it allows different resources but surprisingly in [description](https://hl7.org/fhir/plandefinition-definitions.html#PlanDefinition.action.definition_x_) and examples it is supposed to be activity-definition). Also for structure-map it is supposed to be input as defined [here](https://hl7.org/fhir/plandefinition-definitions.html#PlanDefinition.action.transform)
- Examples show the activity-definition is contained resource in all of the plans. Since plan's activity-definition does not exist on its own it makes sense to keep it contained https://hl7.org/fhir/plandefinition-examples.html
- [$apply](https://hl7.org/fhir/plandefinition-operation-apply.html) suggests that the output could only be CarePlan and the output resources can be contained into CarePlan


[StructureMap](https://github.com/opensrp/fhircore/blob/7b0542c75fde526e30966dac35925bbae370bb7f/android/engine/src/test/resources/plans/child-routine-visit/structure-map.txt). 
- Hypothetically a PlanDefinition can have multiple actions and transforms and code handles it.
- ActivityDefinition, subject are input Parameters for StructureMap.
- Rest is same as before

PlanDefinition added to sync-config.
Rightnow we are running all plan definitions on questionnaire submission, however, we would change it in #1288
