### ISSUE TITLE
[Quest/eCBIS] - Search Patient by ID in ANC Register not working 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1428]
**Describe the bug**
Search Patient by ID in ANC Register not working

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ANC register
2. Search by Patient ID
4. See an error

**Expected behaviour**
1. Ability to filter results based on matching ID

**Comment by shoaibmushtaq25** [comment]
We are saving this **ID** as an identifier and showing it on the Patient Profile screen, e,g, **ID: 74744** as attached in the picture below,
![Screenshot_1658217033](https://user-images.githubusercontent.com/12672919/179696879-4a3a91cd-ba9b-44b1-80a0-5c8b117dcd84.png)

But when we try to search by this identifier, It doesn't find the particular patient record, because we are not filtering based on the identifier in the current implementation. We only filter based on title and patient's logicalId in [PatientRegisterViewModel](https://github.com/opensrp/fhircore/blob/1f891793af9a3be2c7c287d46e091a5cac2f54cf/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/register/PatientRegisterViewModel.kt).
```
 pagingData.filter {
          it.title.contains(event.searchText, ignoreCase = true) ||
            it.logicalId.contentEquals(event.searchText, ignoreCase = true)
        }
```
Hence, the search doesn't work with identifiers right now. Image attached below,
![Screenshot_1658217064](https://user-images.githubusercontent.com/12672919/179696955-e776441c-dea9-4cdb-9e80-24304e3c6466.png)

I think this would be covered in recent ongoing work on the configuration on which @ellykits is working.
cc: @f-odhiambo

**Comment by dubdabasoduba** [comment]
@f-odhiambo This is now fixed by the configurability work

**Comment by dubdabasoduba** [comment]
https://github.com/opensrp/fhircore/discussions/1497

**Comment by dubdabasoduba** [comment]
Closing this issue since it's not fixed by the configuration work.
