### ISSUE TITLE
[Quest/eCBIS] - Search Household by ID in Household Register not working 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1432]
**Describe the bug**
Search Household by ID in Household Register not working

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Household register
2. Search by Household ID
4. See an error

**Expected behaviour**
1. Ability to filter results based on matching ID

**Comment by shoaibmushtaq25** [comment]
We are saving this **ID** as an identifier and showing it on the Patient Profile screen, e,g, **ID: 100010** as attached in the picture below,
![Screenshot_1658144347](https://user-images.githubusercontent.com/12672919/179503739-c434e587-931e-461a-94ca-a49afdde7f62.png)

But when we try to search by this identifier, It doesn't find the particular patient record, because we are not filtering based on the identifier in the current implementation. We only filter based on title and patient's logicalId in [PatientRegisterViewModel](https://github.com/opensrp/fhircore/blob/1f891793af9a3be2c7c287d46e091a5cac2f54cf/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/register/PatientRegisterViewModel.kt).
```
 pagingData.filter {
          it.title.contains(event.searchText, ignoreCase = true) ||
            it.logicalId.contentEquals(event.searchText, ignoreCase = true)
        }
```
Hence, the search doesn't work with identifiers right now. Image attached below,
![Screenshot_1658144822](https://user-images.githubusercontent.com/12672919/179504765-49797806-1684-438c-bfc1-051ac9c3a78a.png)

This would be covered in recent ongoing work on the configuration on which @ellykits is working on.
cc: @f-odhiambo

**Comment by ellykits** [comment]
@shoaibmushtaq25  Can we discuss how we will be addressing this with the configuration code refactor?

**Comment by ellykits** [comment]
We can have the interim fix to main branch before we merge in the fix from the configuration work.

**Comment by shoaibmushtaq25** [comment]
sure @ellykits. I am ok with that.

**Comment by pld** [comment]
I think it can wait for config merge

**Comment by dubdabasoduba** [comment]
@f-odhiambo This is not fixed by the configurability work merge

**Comment by NaveenZehra11** [comment]
still not searching

<img src="https://user-images.githubusercontent.com/90256461/191005401-d3b062f5-3e26-4d19-b54b-78f9fa796cb6.png" width="200" height="400" />


<img src="https://user-images.githubusercontent.com/90256461/191005405-937dc78c-6da5-43dd-9d55-bc125722f19c.png" width="200" height="400" />

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by ellykits** [comment]
Should be fixed by configurable registers. Was this tested using the latest code?

**Comment by ellykits** [comment]
![Screenshot_1663598626](https://user-images.githubusercontent.com/26865532/191045099-eaa10761-bf55-4773-a124-9f1a060a3e4b.png)

**Comment by AnnieMungai** [comment]
@ellykits this is noted. We will test once we merge to main branch.

**Comment by NaveenZehra11** [comment]
@ellykits tested on 
app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc

**Comment by dubdabasoduba** [comment]
Closing this issue since it's now merged on the configuration work cc @AnnieMungai
