### ISSUE TITLE
[Quest/eCBIS] - On HouseHold List Error -> patient DOB cannot not be null

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1435]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

**Screenshot**
<img src="https://user-images.githubusercontent.com/90256461/177764212-f1e3dba8-5312-4717-818d-970fbeb06e4d.png" width="200" height="400" />

**Comment by f-odhiambo** [comment]
App currently failing to syn new data presumably due to this issue CC @NaveenZehra11 @shoaibmushtaq25 @maimoonak

**Comment by f-odhiambo** [comment]
This issue could be an issue with the StrucutreMap and the way we are computing patient age when you select age unknown. The approximate DOB should be computed from the approximate age input filed.

**Comment by maimoonak** [comment]
I am not able to generate null dob by any means width current form. The data might have been entered from somewhere else.
The issue have been fixed in Family Register / Details / Profile only. It would show N/A occur on other registers like ANC/HIV/Appointment as patient age is displayed in list there. Ideally it should be controlled by data entry points i.e. forms. Fixed in PR above

<img width=200 height=400 src="https://user-images.githubusercontent.com/4829880/179269096-69e091c7-7c6e-47c1-9156-db0de456b209.png"/> <img width=200 height=400 src="https://user-images.githubusercontent.com/4829880/179269101-9359b7fe-daac-41ba-90b6-39f8843f9d38.png"/> <img width=200 height=400 src="https://user-images.githubusercontent.com/4829880/179269105-e497aa3a-067a-49fd-9e6e-fa28c3170c06.png"/>

what this rule is supposed to do in family member registration? Maybe we can simplify it.

```
       src.item as calculate_new_date_today -> evaluate(src, today() - 15 'years') as new_date then {
           calculate_new_date_today as patient_date_of_birth where(linkId = 'cd8e3d6d-e9ff-458d-d122-57070bebffaf' and answer.value.count() > 0) then {
               patient_date_of_birth.answer first as patient_date_of_birth_answer then {
                    patient_date_of_birth_answer.value as patient_date_of_birth_answer_value then {
                        patient_date_of_birth_answer_value as patient_age_compare_with_today where(patient_date_of_birth_answer_value <= new_date) then {
                            src.item as head_of_household_check where(linkId ='1e1a206f-1cc2-4e48-8103-b26bf4bd7c3c' and answer.value.code = 'yes') then {
                                head_of_household_check -> bundle.entry as entry, entry.resource = create('RelatedPerson') as relatedPerson then {
                                    src then ExtractRelatedPerson(patient, relatedPerson) "rule_related_person_reference";
                                } "rule_related_person_creation";
                            } "household_head_trigger_check";
                        } "rule_patient_age_compare_with_today";
                    } "rule_patient_date_of_birth_answer_value";
               } "rule_patient_date_of_birth_answer";
           } "rule_patient_date_of_birth";
       } "rule_calculate_new_date_today";
```

**Comment by NaveenZehra11** [comment]
this issue is not replicating on latest apk
cc @maimoonak @f-odhiambo
