### ISSUE TITLE
Build gallery into apk, no changes other than build

### ISSUE THREAD

**Issue by pld** [OpenSRP/fhircore#16]

**Comment by Andati** [comment]
- Branch `initial-app` has app that 
  - fetches patient list from Ona HAPI server
  - has a patient form to register a patient. 
- The code has to be cloned in `android-fhir` project so that it's an android module just like the others (since android-fhir is not published as library yet). Then add the folder in `settings.gradle` file.

To do
- Convert QuestionaireResponse from patient form to PatientResource. Blocked by #240 in android-fhir
- Save the PatientResource
- Sync to HAPI server

cc @pld
