### ISSUE TITLE
[Questionnaires] Adding the ability to save QuestionnaireResponse as In Progress

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1631]
**Describe the feature**
- Currently, when a user exits a form without saving they are only presented with the dialog letting them know that the form content will be discarded. 
![Screenshot_20220914_151214 (copy)](https://user-images.githubusercontent.com/4817531/190204045-f5e00e1b-2abb-4c0e-9836-a879cc1d73d5.png)
- We however want to give the user the ability to save the  QuestionnaireResponse as `In Progress` instead of discarding the form content. 

**Proposed Technical Implementation**
- [x] Add a boolean `canSaveDraft` to the method launching the Questionnaire. 
    - [x] This boolean will be `false` by default.  
- [x] If the `canSaveDraft` is set to `true` then the dialog that appears when a user exits the form will update to have 2 options. 
    - [x] **Save Partially** -- Allows the user to save the questionnaire partial by setting the QuestionnaireResponse `QuestionnaireResponse.status` property to `in progress`, then redirects to the screen before the questionnaire render. 
    - [x] **Discard** -- This discards all the inputs on the form and closes the Questionnaire render page, then redirects to the screen before the Questionnaire.
- [x] Resource extraction should only be done when the `QuestionnaireResponse.status` == `completed`  

**Related SDK Issue**
- https://github.com/google/android-fhir/issues/1608

**Related Discussion**
- https://github.com/opensrp/fhircore/discussions/1557

**Comment by pld** [comment]
Cool, and these would get synced to server, and then down to other devices?

**Comment by dubdabasoduba** [comment]
> Cool, and these would get synced to the server, and then down to other devices?

@pld this is interesting. With the current sync setup yes. I see situations where these don't need to be synced. 

We might want to add a configurable way to mark resources that shouldn't be synced up to the server.

**Comment by pld** [comment]
K yea maybe, it's not necessarily bad, it's a feature we've seen requested, it does make me wonder about increased risk of conflicts

**Comment by dubdabasoduba** [comment]
@allan-on Any feedback on this?

**Comment by allan-on** [comment]
@dubdabasoduba The implementation is done and the associated PR is under review. 
A couple of things came up during the implementation. 
- The confirmation dialog has 2 options i.e. `Discard` (changes) or `Save partially ` (draft). Ordinarily, the dialog would have `Cancel` as an option to return back to the form. With that option not available when saving a draft, to achieve the same, AlertDialog implementation is refactored to allow showing a dismissable one so that one can click outside the dialog to dismiss it and get back to the form. 

- SDC QuestionnaireResponse validation is skipped when saving the response since the QuestionnaireResponse would most times be incomplete but a custom validation implementation avoids saving completely empty responses.

**Comment by dubdabasoduba** [comment]
@allan-on how do we specify if the Questionnaire needs to check for in progress? or is this default for all questionnaires now?

**Comment by FikriMilano** [comment]
Had a conversation w @jingtang10.

It's not possible to prevent certain resources getting sync to the server, we don't have the API to do that yet.
But it's a reasonable thing to add.

Our use case is: `Prevent in-progress Questionnaire Response to sync up`

**Comment by jingtang10** [comment]
We should do it by using local-only resources, which the sync API will ignore in all its jobs. And when the local-only resouce needs to be synced, we should have an API that allows the app to "flip" the local-only flag, and the sync API should pick it up.

**Comment by FikriMilano** [comment]
@jingtang10 yeah, that's the simplest way to do it 👍

**Comment by ndegwamartin** [comment]
For our current use-case we don't need to prevent the sync up because the **in-progress** QuestionnaireResponse is not extracted yet to the output resources _e.g. Patient, Person e.t.c_ 

The feature will come in handy though when we want to implement some sort of edit window after data is collected on the device before a sync up.
