### ISSUE TITLE
Performance enhancement on loading the questionnaires. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1730]
**Describe the enhancement**
- [ ] Review the code we are using to trigger the rendering of questionnaires. The questionnaires take a lot of time to load sometimes even causing the Black screen of death on devices. 
    - [ ] Low ram devices end up breaking because of this. The OS kills the processes to render the forms due to the heavy demands on resources.  
- [ ] It seems like most of the time is used loading the FHIR context. Can we maybe load this earlier and just have it on memory?
     - [ ] Review whether different forms can use the same context. This way we don't have to load the FHIR Context for every form. 
https://user-images.githubusercontent.com/4817531/195215634-cccf4754-4a37-48b4-a81f-96064478249a.mp4

**Acceptance criteria**
- [ ] Enhance the performance here for forms to render faster.

**Comment by pld** [comment]
@f-odhiambo this is an example of the type of the issue I was thinking of for the "UI Performance Improvement" roadmap item

**Comment by allan-on** [comment]
Prior to 
The primary reference was the Android Developers' documentation on best practices for inspecting and improving performance [Guide to app performance](https://developer.android.com/topic/performance)

The code inspection and performance investigation in relation to Questionnaires rendering focused on: 

- App Startup/Activity loading
- Slow rendering (jank)
- Any long-running work
- Operations in the background such as I/O and networking

The main approaches in performance inspection are either **manual** or **automated**: 

To begin with, I started with the manual inspection
The following are the tools considered for this inspection: 

1. Android Studio Profiler - To analyse memory allocations
2. Firebase Performance Monitoring - To get the QuestionnaireActivity loading and rendering performance metrics

**Memory allocation inspection** 

This is to check on memory usage when loading Questionnaires since some (lower-end) devices struggle and end up showing a black screen

The following observations were made based on the heap dump using the Studio profiler when loading the QuestionnaireActivity: 

- A significant amount of memory is consumed. The numbers are merely for comparison since the SDK sample app is a much lighter/smaller application and loads Questionnaires much faster. 
    - Comparison between the SDK sample app vs the Quest app shows
        - App heap shallow size → 12MB vs 80MB
        - App heap retained size → 50MB vs 675MB
        - Leaks → 1 vs 2
        - Classes → 2600 vs  5900

    - Project classes that consume the most memory are:
        - FhirContext ~ 35MB
        - RegisterViewModel ~ 26MB
        - ResourceData ~24MB
        - LibraryEvaluator
    - Non-project classes
        - Object[] ~ 85MB
        - ArrayList ~84MB
        - LinkedHashMap ~ 24MB
            
- Memory leaks are associated with:
    - PinLoginActivity
    - ReportFragment

Suggested next steps. 

1. Tracing code execution times related to initializing and launching the QuestionnaireActivity through custom code tracing or  Firebase performance monitoring
3. Look into how to optimise memory consumption - optimising object creation and reuse for the classes identified above
4. Looking into any optimisation around code execution times - based on associated metrics from 1. 
5. Fix the memory leaks and any other issues identified

**Comment by f-odhiambo** [comment]
PR closed https://github.com/opensrp/fhircore/pull/1834
