### ISSUE TITLE
[Quest] Use Sentry to track and monitor performance bottlenecks on quest and FHIR Core 

### ISSUE THREAD

**Issue by LZRS** [opensrp/fhircore#1809]
**Name of feature**

Add Sentry performance monitoring to FHIRCore 

**Description of feature**
Basically set up FHIRCore to work with Sentry, and get notified on updates on performance as we continue to add features on FHIRCore.

This would help keep track of performance across the FHIRCore apps, detect high impacts on performance and get breadcrumbs on performance issues

cc @dubdabasoduba

**Comment by pld** [comment]
Cool, can you make this issue more specific? Let's constrain the scope of this to be as small as possible, MVP style, so that it is easier to complete and come up with an implementation plan. We want to start small and focus more on the minimum harness infrastructure and reporting -- then we can add over time
