### ISSUE TITLE
Edit related person fields to registration questionnaire

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#185]
Once you have created a new related person, you can retrieve their details on the edit patient profile details page and updated the files accordingly. This should update the bundle resources i.e Patient resource and RelatedPerson resource respectively  

Attached mock
<img width="307" alt="Screen Shot 2021-05-31 at 12 12 31 PM" src="https://user-images.githubusercontent.com/4540684/120174267-911ea480-c20d-11eb-8fe9-d6ee63f258e7.png">

**Comment by f-odhiambo** [comment]
We need to unblock this feature implementation. At the moment we do not have a way in which we can be able to extract multiple resources from a single questionnaire

**Comment by f-odhiambo** [comment]
**Update**
1. Structure map based extraction 
2. Definition support to be used in place once UUID work is complete

**Comment by MuhammadSalman-7214** [comment]
This is being blocked until Epharim's work completes on ticket https://github.com/opensrp/fhircore/issues/184

**Comment by ekigamba** [comment]
@MuhammadSalman-7214 I think you can proceed from this branch https://github.com/opensrp/fhircore/tree/issue/184-add-related-persons-fields because this PR is possibly going to be blocked for a while.


The required datacapture release for this branch has also been released here https://github.com/google/android-fhir/packages/677325 and contains the latest master from Android FHIR SDK + StructureMap-based extraction PR

**Comment by MuhammadSalman-7214** [comment]
okay, thanks for informing @ekigamba

**Comment by f-odhiambo** [comment]
@ekigamba Assigning you this task on Edit pateint
