### ISSUE TITLE
[Configuration] Filtering registers based on resources attributes

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#2036]
**Is your feature request related to a problem? Please describe.**
- When a CHSS logs into their application, they should only have access to data that is from the CHAs under them. They should also be able to view a list of only their CHAs on the CHA register. 

**Describe the solution you'd like**
- [ ] When a CHSS opens the patient data registers from the CHA profile the records displayed should be filtered by the. CHA (Practitioner ID)
     - [ ] All the records created by the app are tagged by the `practitioner Id` on the `meta.tag` attribute.  
     - [ ] Write a filter that can accept expressions (probably) FHIR path to filter the resources displayed on the register by the clicked practitioner Id. 

- [This](https://github.com/opensrp/fhircore/issues/2001) work by @SebaMutuku filters resources in a LIST view by specific FHIR path expressions. I think we can extend it to filter all the registers.
 
**Describe alternatives you've considered**
N/A

**Additional context**
- A CHSS acts as a supervisor to the CHA. A CHSS is normally assigned 5-10 CHAs under them. CHSS is responsible for reviewing the CHA work and thus needs to see each CHA's updated data after P2P or a sync.

**Comment by FikriMilano** [comment]
@dubdabasoduba @AnnieMungai 
since CHSS should only see the work from CHAs, is it possible to sync based on the related CHAs?

**Comment by pld** [comment]
Couldn't we handle this by using CareTeam sync as is? If we assign the CHSS to all of the CareTeams any of its CHAs are in, wouldn't that handle this?

**Comment by dubdabasoduba** [comment]
> Couldn't we handle this by using CareTeam sync as is? If we assign the CHSS to all of the CareTeams any of its CHAs are in, wouldn't that handle this?

@pld @FikriMilano The CHSS device is used as a data store. These devices hold the data from all the CHAs supervised by the CHSS. It will occasion also hold data for other CHAs not supervised by the CHSS. This is because the CHSS is allowed to P2P sync will other CHAs in order to transmit their data to the server. 

With the above context, a CHSS is allowed to view a replica of the registers on the CHAs device.  This issue is to make sure the data shown on these CHA replica registers is data that belongs to the CHA in question. 

e.g if the CHSS selects CHA 1 and tries to view the Household register for CHA 1 then only families tied to CHA 1 should show up as much as the CHSS device has household data from other CHAs.
