### ISSUE TITLE
[Quest] Edit patient details missing info on some of the input fields previosuly captured  

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2094]
**Describe the bug**
Edit patient details has missing fields when invoked 

**To Reproduce**
1. Go to Patient List 
2. Click on a patient 
3. Go to menu Item and click edit 
4. See the error

**Expected behavior**
All previously filled detail for the patient should be pre-populated both on input fields and selection drop-downs/radio buttons

**Smartphone (please complete the following information):**
 - Device: Emulator or Physical device 

**Additional context**
N/A

**Comment by FikriMilano** [comment]
Facing issues with sync, got a 401 error using preview server

**Comment by FikriMilano** [comment]
replicated, apparently it's not mapping all fields

<img width="250" alt="image" src="https://user-images.githubusercontent.com/62053304/221576455-97f43737-0a22-4dab-98d8-6cbe43eada49.png">  <img width="250" alt="image" src="https://user-images.githubusercontent.com/62053304/221576475-aea3d45c-7517-410b-b829-350772c26995.png">

**Comment by dubdabasoduba** [comment]
> Facing issues with initial sync, got a 401 error using preview server

Which Preview server? All development was moved to the Stage instance.

**Comment by dubdabasoduba** [comment]
@f-odhiambo is this occurring after the new SDK dependency addition?

**Comment by FikriMilano** [comment]
> > Facing issues with initial sync, got a 401 error using preview server
> 
> Which Preview server? All development was moved to the Stage instance.

@dubdabasoduba This is resolved, turns out there was a new keycloak credentials

**Comment by FikriMilano** [comment]
Replicated.

Conclusion:
Found out that, some patients have their fields mapped including: First Name, Middle Name, Surname, DoB and Gender.
But there are missing fields too: OpenSRP ID, National ID Number, Is family head.

Another note: some patient also can't map their First Name field.

**Comment by dubdabasoduba** [comment]
@FikriMilano is this because of something on the SDK and FHIR Core or Is this because of how the content is authored?

**Comment by FikriMilano** [comment]
@dubdabasoduba I could be wrong. But I doubt it's the SDK.

I think it's FHIR Core itself and how the content is authored

**Comment by FikriMilano** [comment]
@f-odhiambo @dubdabasoduba 
Fatal mistake, note here.
There are two ways to display a questionnaire response in a questionnaire.
1. QR from DB
2. QR from population

In most cases, the QR from DB returns null, so we're generating a QR from population.

Problem is:
The resources that's populated only contains a Patient, which doesn't have OpenSRP ID, National ID Number, and Is family head.
And.
The Questionnaire doesn't have initialExpression for OpenSRP ID, National ID Number, and Is family head.

That's why some fields (OpenSRP ID, National ID Number, and Is family head) are not mapped.

Provided 2 solutions:
1. Add initialExpression to the missing fields and make sure to extract the resources that are supposed to have the mapped value
I prefer this.
Questions are:
   1. Where do we keep OpenSRP ID and National ID Number?
   2. What's the indicator to decide a Patient Is a family head?
   3. If at some point, we have a new field and the answer is not relevant to any FHIR resource. This means we can't extract this answer to a resource to save it, we can't populate that resource, and we can't map the answer to that new field. 
   In this case, what do we do?
2. Only retrieve QR from the database
Have to make sure it's not null.

**Comment by dubdabasoduba** [comment]
This is interesting. Why do we have them as `null`? Don't we send or retrieve them from the server? 

I would go with option 2. This does not add any overhead in pre-processing. You just pick the relevant QR and display it's contents.

**Comment by FikriMilano** [comment]
1. I don't know why the QR from DB are null as well. I can investigate this further.
2. Option 2 is nice too. My hesitation is, why are we populating resource in the first place? can you remind me?

**Comment by FikriMilano** [comment]
To summarize on earlier discussion w Francis:
Add an error message to let the user know, if a QuestionnaireResponse:
- Is not synced properly, or
- Results the forms has missing answers

Let me know if this will solves your concerns @f-odhiambo

**Comment by FikriMilano** [comment]
- [ ] Fix QuestionnaireResponse from DB
- [ ] QuestionnaireResponse from Population
  - [ ] Fix initial expressions
  - [ ] A bug when the OpenSRP ID is pre-populated when creating a new patient
 - [ ] Display error message when QR is not usable
