### ISSUE TITLE
Redirect more intelligently when globally capturing exceptions

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#2193]
**Describe the feature request.**
(from @dubdabasoduba)

My assumption is this would then redirect the user to the PIN or username/password login page since the App Ids were already entered into the app. If yes I think that's fine but we can consult the Design team.

I think it would be better to redirect to the home page assuming the crash is happening somewhere else other that the home page. We could redirect to the Login pages if the crashes happen on the home page. We could then redirect to the setting page if they happen on the login pages.

My reasoning for the above proposal is to still give the use a change to use the app if some pieces of it are usable.

I realise it might be too much or over engineering of some sought though.

**Additional context**
Originally in this PR, https://github.com/opensrp/fhircore/pull/2161

**Acceptance criteria**
- Redirect when exception thrown on login page is to settings
- Redirect when exception thrown on home page is to login
- Redirect when exception thrown on internal page is to home page

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.

- This might not be possible to test since it requires generating an unexpected exception, which should be hard to do

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by pld** [comment]
One thing, @dubdabasoduba this assumes the exception means the current screen doesn't work, which is sometimes but not always the case, I guess probably safer to assume that's true and have a "back-off" of redirects like you're proposing.

But, if the exception was due to a background activity or a click event, reloading the current screen would be least surprising to the user

**Comment by ellykits** [comment]
My findings while resolving the global exception handler bug.

- The global exception handler freezes the application (with application not responding - ANR response) unless the process is killed. 
- If the exception handler is set in the `AppMainActivity` or at the `Application` level, the above closes the app since we use single activity architecture. Here is the code for setting the excepting handler
```kotlin
 Thread.setDefaultUncaughtExceptionHandler(QuestExceptionHandler(this))
```
- If the handler is set in the `QuestionnaireActivity` and the app is re-directed to the `AppMainActivity`, we still get a crash (missing configurations which can be addressed by re-loading the configurations from `ConfigurationRegistry`).

It's important to note from the above findings, that the default exception handler should not be set in the MAIN activity neither should we set it at the application level. Right now we only have P2P and Quesionnaire activities launched independently.

**Comment by ellykits** [comment]
Based on my findings: my recommendation is not to pursue this Global exception handler. Most of the exceptions that we were trying to handle here were QuestionnaireActivity-related, and they have been addressed.

**Comment by pld** [comment]
ok
