### ISSUE TITLE
Multi-Language support

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#25]
We need a mechanism to support changing the app language based on preference by the app user. The SDK does this by checking the global setting of the phone and then setting the translation of the FHIR resource

1. Add translation for different languages for LTR Locale
2. Add translation for different languages for RTL Locale

**Comment by pld** [comment]
Multi-language splits into at least 2 components:

1. support multi-language for non-configurable parts of the app
2. support multi-language for configurable parts of the app driven by FHIR

I think multilanguage is natively supported in FHIR, which should cover (2), let's confirm that and add some examples of that here.

To do (1) through multi-language FHIR resources we'd need to drive all text in the app with FHIR resources, including the splash screen, login screen, settings screens. It's not clear to me we'd want to do that, and if not we'd have two parallel multi language systems: what we use now for multi-language opensrp for (1) multi-language FHIR resources for (2).

We'd also need to support, and perhaps this is a separate issue
- [ ] setting the default language for the app
- [ ] changing and saving a change to the language for the app

**Comment by maimoonak** [comment]
**Preliminary research**

FHIR internationalization support : https://www.hl7.org/fhir/languages.html

Common languages include https://www.hl7.org/fhir/valueset-languages.html#definition

**How to filter language specific data** (may be not needed if we can make some compromise on data, and size)

FL#1 - To request for specific languages a header `'Accept-Language: de-DE'` can be sent [could not determine fallback mechanism as rightnow NOT working on hapi-fhir-server]

FL#2 - Request can has a query param to filter out resources with specified language attribute value (this forces request to filter out language specific data. there is no default fallback mechanism)

**Options to specify language**

(Implementer needs to make sure to follow one standard protocol and FHIR does not do any check on content and the tag)

**LT#1** - Each resource in FHIR has a language tag (optional) including Patient, Observation, Encounter which specifies the default language for resource 

The language can also be specified by xml:lang tag on html elements (< div >) in resource.

Might be easiest to implement but not the best. It would lead to duplicate records. Querying over data that is supposed to show for people using multiple languages would also be problematic. Since it does not have a default language fallback we may face issues in case all translations have not been done or some are done at a later stage.

**LT#2** - **[Translation extension](https://www.hl7.org/fhir/extension-translation.html) can be used to specify translations for languages for any string or markdown content**

Might be best for system as all resources can follow this including Location, ValueSet, etc.  All data would be with same resource and can lead to heavy packets while syncing if we do not find how data is filtered for languages. May also consume more time (could be negligible as well) when displaying language specific views

**LT#3** - **Translations for CodeSystem and ValueSet via [CodeSystem.concept.designation](https://www.hl7.org/fhir/codesystem-definitions.html#CodeSystem.concept.designation)**

Fallback implemented with a base language. Header filter does not work. Might be best for managing translations for ValueSets however, then we would need to use a different strategy for other Resources

**LT#4** - [Translatable Extension](https://www.hl7.org/fhir/extension-elementdefinition-translatable.html) on element those are likely to be rendered via UI to inform tool to handle it accordingly

If we want to manage translations on our own and just want to alert UI tool to process the resource according to available translation. May be not for our usecase.

**Comment by pld** [comment]
I understand this would be nice to have, but is this required for any currently in progress apps?

**Comment by f-odhiambo** [comment]
I think it would be prudent to have this also going on in the background but I agree it is nice to have feature - Low Priority

**Comment by f-odhiambo** [comment]
Related to this, Fred would like us to have an implantation of this , where we have an activity or fragment to change language locale based on the issue [#503](https://github.com/google/android-fhir/issues/503)

**Comment by ndegwamartin** [comment]
Closed by https://github.com/opensrp/fhircore/pull/262
