### ISSUE TITLE
Add style checks

### ISSUE THREAD

**Issue by pld** [OpenSRP/fhircore#28]
Consider ktfmt, https://github.com/facebookincubator/ktfmt

https://github.com/google/android-fhir/discussions/246

**Comment by pld** [comment]
Also for reference, https://github.com/google/android-fhir/issues/290#issuecomment-794620897

**Comment by vincent-karuri** [comment]
The approach in the PR will use Spotless - similar to what Google has done. I think the main selling point is that you can add multiple linters to augment each other's strengths.

One thing I don't like too much is that the linting process fails as part of the main Github Actions workflow that builds/compiles the code (I guess it's possible to break it off though).

Another option is to use [Codacy](https://docs.codacy.com/repositories-configure/code-patterns/#using-your-own-tool-configuration-files), similar to OpenSRP projects atm, which uses [detekt](https://github.com/detekt/detekt) as a linter - seems quite popular and under active development. Codacy UI is nicer and provides a separate enforceable code-quality check on Github. 

Either way, I think Spotless is good enough for now and provides a uniform set of rules as what we'd expect in the Android FHIR SDK. Since we'll be contributing to it, it would be better if we can have familiar workflows across both projects.

**Comment by pld** [comment]
Cool, yea agree w/that, there are be trade-offs but staying aligned forces our hand
