### ISSUE TITLE
CHW/ANC SubTask - User can record a birth outcome 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#292]
@isabelcshaw Some more info is required here

**_Mock attached_** 

<img width="618" alt="Screen Shot 2021-09-07 at 11 10 21 AM" src="https://user-images.githubusercontent.com/4540684/132325530-083d77fa-1a74-4a5e-8cd2-2a5b35276e89.png">

**Subtasks**

- [ ] #553

**Comment by isabelcshaw** [comment]
For all clients with an active pregnancy, the ability to record a birth outcome will be added to their profile view. In order to record a birth, the user will hit the option menu in the top right corner and "record birth outcome" will be one of the menu options. (See image of the profile view below.) This will open a short questionnaire. _Fields to be confirmed_. 

The submission of that questionnaire will do two things. First, it will close out the woman's ANC plan definition and automatically add a PNC plan definition to her care plan. Second, if the outcome is a live birth, then it will prompt the user to register the newborn. (This is the current logic in OpenSRP.) 

<img width="259" alt="Screen Shot 2021-07-15 at 6 37 47 PM" src="https://user-images.githubusercontent.com/12836913/125878556-b9249583-9b4a-4bba-a630-88ccce814043.png">

**Comment by pld** [comment]
How do we record this in FHIR?

**Comment by f-odhiambo** [comment]
Initial research shows this can be recorded using the following structure definitions using [ANC Observations](https://build.fhir.org/ig/who-int/anc-cds/branches/feature_updated_dataelements_with_decision_tables/StructureDefinition-anc-observation.profile.json.html)

1. Normal birth - Not found yet
2. [Preterm Birth](https://build.fhir.org/ig/who-int/anc-cds/branches/feature_updated_dataelements_with_decision_tables/StructureDefinition-anc-end-de4.html)

we would also like to track the following  observations i.e 
1. [Birth weight](https://build.fhir.org/ig/who-int/anc-cds/branches/feature_updated_dataelements_with_decision_tables/StructureDefinition-anc-end-de6.html)
2. [Whether last live birth was preterm](https://build.fhir.org/ig/who-int/anc-cds/branches/feature_updated_dataelements_with_decision_tables/StructureDefinition-anc-b6-de12.html)
3. [Number of live births](https://build.fhir.org/ig/who-int/anc-cds/branches/feature_updated_dataelements_with_decision_tables/StructureDefinition-anc-b6-de11.html)
4. [Number of stillbirths](https://build.fhir.org/ig/who-int/anc-cds/branches/feature_updated_dataelements_with_decision_tables/StructureDefinition-anc-b6-de13.html)

CC @isabelcshaw @pld

**Comment by f-odhiambo** [comment]
Something to review here too https://nhsconnect.github.io/FHIR-Maternity-Record/explore_pregnancy_outcome.html 

CC @isabelcshaw @pld

**Comment by isabelcshaw** [comment]
@f-odhiambo I'd say the most important thing to prioritize here is ensuring we can trigger the registration of a new family member (the infant) from this workflow. 

LMH currently collects pretty limited information here - mostly whether there was a live birth, how many fetuses, and the date. We'll likely update this questionnaire with them, but I think that's enough for a proof of concept.

**Comment by f-odhiambo** [comment]
@dubdabasoduba @AnnieMungai Do we need this for LMH?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba @AnnieMungai Do we need this for LMH?

@f-odhiambo For the 15th release not really but we might need it later. @AnnieMungai just to confirm we will have some ANC pieces right?

**Comment by f-odhiambo** [comment]
This I believe is the exit from ANC  and Entry to PNC 

CC @dubdabasoduba  @AnnieMungai

**Comment by AnnieMungai** [comment]
@f-odhiambo I confirm this will be required for eCBIS and this exits a client from ANC to PNC ([see this issue](https://github.com/opensrp/fhir-resources/issues/42))
