### ISSUE TITLE
Login process shows a black screen after entering the login PIN

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#3208]
**Describe the bug**
During _Login_, after inputting the login PIN there is a noticable delay when navigating to the register screen. This manifests as a black screen and the app takes a few seconds before showing the syncing screen. 

**To Reproduce**
- install the app.
- input the app ID
- input the username and p/w
- input PIN and observe the black screen and dial-pad showing

**Expected behavior**

- After inputting pin the app should start syncing immediately.

**Screenshots**

https://github.com/ona-health/sid-dto-fhir-resources/assets/84722169/361481b3-fc50-4bd3-8c90-a7eff80eced4

**Additional context**
Related to the two project tickets here:
- https://github.com/ona-health/sid-dto-fhir-resources/issues/367
- https://github.com/ona-health/hisp-wdf-fhir-resources/issues/276

**Comment by ndegwamartin** [comment]
We need to conduct these steps for this ticket:
- [ ] Troubleshooting to figure out what is causing the issue (To be documented on this issue)
- [ ] Come up with a fix that is feasible (To be documented on this issue)
- [ ] Actual implementation of the fix above

**Comment by f-odhiambo** [comment]
@qiarie Any update on this ? When can we get a PR out ?
CC @ndegwamartin

**Comment by qiarie** [comment]
@f-odhiambo 
I have been carrying out investigations on the cause and probable fixes to the issue.

It takes about 7 seconds between the `PinLoginActivity` being destroyed and `AppMainActivity` starting. It is during this interval that the black screen shows.

The main issue that I identified as the cause is the inflation of the XML `NavGraph` during `AppMainActivity` `onCreate` which takes some time to complete.

Solutions implemented, and which didn't resolve the issue.

- Adding a window background in the theme to avoid the black screen
- Applying enter and exit transition animations
- Optimisation of `onCreate` and `onResume` to remove unnecessary processing in the main thread
- Optimisation of the `RegisterFragment`'s `onCreateView` to reduce work on the main thread

MalawiCore have solved the black screen issue. Their approach was by using a compose definition for navigation components. This will require a rewrite of FHIRCore's navigation.

**Comment by qiarie** [comment]
Note:

- This issue appears in older devices

**Comment by qiarie** [comment]
#### Pixel 7 - Android 14

https://github.com/user-attachments/assets/b8a78053-3633-48ed-ae71-9ac9d5448cc5


#### Pixel 7 AVD - Android 14

[Pixel_7_AVD.webm](https://github.com/user-attachments/assets/690f2923-c783-4698-96c1-db951cf1e156)

**Comment by Naima-Bashir** [comment]
@qiarie @ndegwamartin  This has passed QA on the following apks:

**Apk Version** - `[quest-gizEir-release.apk]`
**Device** - `Samsung Tab Lite`
**Android version** - `13
`

**Apk Version** - `[quest-diabetesCompass-release.apk]`
**Device** - `Samsung Tab Lite`
**Android version** - `13`
