### ISSUE TITLE
Difference in Questionnaire pagination button styles 

### ISSUE THREAD

**Issue by LZRS** [opensrp/fhircore#3212]
**Describe the bug**
A paginated questionnaire when rendered, the "previous"/"next" button have distinctly different styling from that of the "submit" button

**Expected behavior**
The button should probably be similar styled or may be allowed to be configurable

**Screenshots**

<img width="50%" width="50%" src="https://github.com/opensrp/fhircore/assets/12814349/e0aa35ba-4154-4a4b-ac1b-868b75b72727">

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

**Comment by allan-on** [comment]
Hello @rowo @HenryRae The Questionnaire submit buttons in OpenSRP appear to be differently shaped compared to the submit buttons in the Google SDK as seen in their demo apps. 
When we have paginated Questionnaires, the `previous`/`next` and submit buttons have a different look
Is this by design? cc @pld 


<img src="https://github.com/opensrp/fhircore/assets/16164649/5f6b30bd-85f4-4d2d-be17-b8111985d40c" height=550 width=270 />
| 
<img src="https://github.com/opensrp/fhircore/assets/16164649/c52f2fef-d872-4fe2-89da-b1ee0cae90b1" height=550 width=270 />

**Comment by HenryRae** [comment]
Here's how [forms](https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-(OpenSRP)-Apps-~-Design-System?type=design&node-id=9893-76825&mode=design) were designed. Thus this what should be followed, however we are happy to adjust the designs to what we are able to archive technically.
