### ISSUE TITLE
Make the Apply Filter/ Sync Data button on the Multiselect Widget sticky

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3626]
### Context
- One must scroll after selecting Locations to filter to see the Apply Filter/ Sync Data button. 
- Making the button sticky would make it easier to find.  The idea is to remove it from the bottom of the view and make always appear without scrolling

### To Reproduce
Steps to reproduce the behaviour:
1. Log into the app.
2. Select a region or several - make sure they have inventory.
3. Tap on sync after selection.
4. Wait for sync to complete - it takes 3-5minutes based on the selected regions.
5. Navigate to the filter button on the map view and tap on it.
6. Select a region
7. Locate the APPLY FILTER button

###. Expected behaviour
- [ ] One should not have to scroll to see the APPLY FILTER button

**Comment by Lentumunai-Mark** [comment]
**Key Changes**
- BottomBar in Scaffold: The button is moved to the bottomBar of the Scaffold, ensuring it is always visible and sticky at the bottom of the screen.
- Removal of Button from LazyColumn: The button is no longer part of the scrollable content.
- Padding with paddingValues: The padding of the main content respects the Scaffold layout to prevent overlaps with the bottom bar.
Expected Behavior
The "Apply Filter/Sync Data" button will always be visible, even if the user scrolls through the list of locations.

**Comment by Lentumunai-Mark** [comment]
closed by this [ PR](https://github.com/opensrp/fhircore/pull/3629)
