### ISSUE TITLE
Data dictionary for covid-19 app needed

### ISSUE THREAD

**Issue by Andati** [opensrp/fhircore#41]
Data dictionary to define:-
- [x] Patient form questionnaire - fields required and the correct labels & translations
- [x] Vaccine form questionnaire - fields required and the correct labels & translations

**Comment by vincent-karuri** [comment]
I think this can be generalized to other apps as well

**Comment by pld** [comment]
Doesn't defining the patient and vaccine questionnaires satisfy this issue?

CC @rowo

**Comment by pld** [comment]
Or said another way, does defining the patient and vaccine questionnaires close this issue?

**Comment by pld** [comment]
What would go in the Excel that wouldn't go in fhir resources? We want to make non-devs responsible for defining fhir resources to share responsibilities

**Comment by Andati** [comment]
Currently, excel is where the PM and client discuss the fields. The order, label, choices, mandatory, relevance, etc of the fields.
Once that is done, then it's translated to a form.

**Comment by pld** [comment]
Good point, the hope here is that instead of iterating on the excel, we'd do the same on the questionnaire. The clients will preview the questionnaire in an online FHIR resource renderrer and give feedback based on that, which gives them an experience closer to the actual user experience, then the analyst iterates on edits to the form without dev intervention.

CC @rowo I believe this is inline with what we discussed and a change in process you suggested

CC @dubdabasoduba eventually we'll want that questionnaire player in opensrp web, but to start any publicly hosted FHIR questionnaire renderer will work

**Comment by rowo** [comment]
@pld @Andati Yes, this would be nice. One of the process improvements is showing forms to clients as close to how they will appear in the end state as early in the requirements discovery process as possible. Currently, I think it's too much trouble or takes too long. But if prototypes can be moved earlier in the progress, then user testing can be moved earlier and  we can reduce late changes (that's the hope at least).

The near-perfect end goal could be something like [Codepen](https://codepen.io/pen/) or [w3schools' TryIt Editor](https://www.w3schools.com/cssref/tryit.asp?filename=trycss_sel_class). This would allow seeing both behind the scenes logic and how things will look to the end user. I'm sure that's a few versions down the line.

**Comment by mberg** [comment]
I want to flag this exists

https://lhcformbuilder.nlm.nih.gov/

We want to move away from the developers needing to program the forms.
