### ISSUE TITLE
Retrieve & Sync Patient Registration Questionnaire  from HAPI and not assets folder

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#429]
**As a subtask of #414**
Load the [patient-registration.json ](https://github.com/opensrp/fhircore/blob/main/android/app/src/main/assets/patient-registration.json)from the server-side and not the assets folder as Referenced here: https://github.com/opensrp/fhircore/blob/5ebff99e5072907b9c7e27cc8ead7357b32f8e29/android/app/src/main/java/org/smartregister/fhircore/activity/PatientListActivity.kt#L103

**Acceptance criteria**
**Option 1 :** 
- [ ] Create two registers one for Covax and one for CHW/ANC
- [ ] If one selects the Covax Clients register and clicks on Register new patient, load the [Covax registration questionnaire sample](https://fhir.labs.smartregister.org/fhir/Questionnaire/754)
- [ ] If one selects the CHW/ANC Register and clicks on Register new patient, load the [CHW/ANC questionnaire sample](https://fhir.labs.smartregister.org/fhir/Questionnaire/207)   - _Needs SW translation_ 

NB. On click for each register will load either an empty list/populated patient list  with Register patient button 

**Mocks**
_**NB. Replace RDT with ANC**_

<img width="383" alt="Screen Shot 2021-07-23 at 1 14 03 PM" src="https://user-images.githubusercontent.com/4540684/126768379-7d13ca9f-9feb-41cc-8dc8-420882612c67.png">

**Option 2:**
**TBD**

**Comment by dubdabasoduba** [comment]
**Context**
- With the R&D to edit patient data on going for OpenSRP web, we need a way to Identify which Questionaire Resource to load for each patient we try to edit. 
- For this to happen we need to fetch the registration Questionaire Resources from the server. 
- We also need a way to Identify which questionnaire resource was used to create the patient. 

**Changes that affect the Android client**
- As mentioned above the clients currently read the Questionaire resource from the app assets. We would like to be able to fetch this from the server. 
- Then figure out a way to map each registration questionnaire resource to its correct module. 
- Figure out how to identify which questionnaire resource a patient was created from, this will help the web instance know what questionnaire to use when trying to edit the patients.

**Comment by maimoonak** [comment]
Although not related however, now we need to start thinking in terms of what actually we are building.. 
- Is it a different implementation which we are providing and that would provide base for other implementations (means that We have an IG ([Implementation Guide](https://www.hl7.org/fhir/implementationguide.html) which would allow people to import all metadata), 
- Would this IG depend on other IGs as well, 
- What are details for our IG i.e. url, name, etc, how we would register it with [FHIR](https://wiki.hl7.org/FHIR_Implementation_Guides) and [registry portal](https://www.fhir.org/guides/registry/)
- Is it one single IG or multiple IGs

We would also want to add a workflows i.e. add these to specific [PlanDefinition](https://www.hl7.org/fhir/plandefinition.html) and try automating the register/app specific metadata as well.

Aside from above for current issue we would need to 
- add questionnaires to server
- sync questionnaires and keep them updated (For now sync like we do for patient when launching FHIRApplication, and later with proper syncing setup)
- Load the questionnaire from FhirEngine as Resource [instead of assets ](https://github.com/opensrp/fhircore/blob/main/android/app/src/main/java/org/smartregister/fhircore/viewmodel/QuestionnaireViewModel.kt#L36), and pass the key of form from register click method to questionnnaire activity which would be later on derived by workflow

**Comment by f-odhiambo** [comment]
@maimoonak on the following points 

1. add questionnaires to server **- Updated the links to the test questionnaires for this implementation on the HAPI FHIR Server**
2. sync questionnaires and keep them updated (For now sync like we do for patient when launching FHIRApplication, and later with proper syncing setup) **- TODO**
3. Load the questionnaire from FhirEngine as Resource instead of assets , and pass the key of form from register click method to questionnnaire activity which would be later on derived by workflow **- TODO**

**Comment by f-odhiambo** [comment]
We will also need to tag which patient belongs to which register @maimoonak @dubdabasoduba

**Comment by pld** [comment]
I think we should just call it "ANC" not "CHW/ANC" because "CHW" isn't a health vertical it's a type of user so it would not make sense as a register (neither would "RDT" but that's fine, since we're removing it :)

**Comment by maimoonak** [comment]
@f-odhiambo @dubdabasoduba We also need the questionnaire record-vaccine.json in questionnaires and load in same way. Plz add the link to vaccine questionnaire as well

**Comment by f-odhiambo** [comment]
Here is the link to the Record Vaccine questionnaire - https://fhir.labs.smartregister.org/fhir/Questionnaire/800
