### ISSUE TITLE
Search for patient using Patient ID 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#481]
We need to implement search by Patient ID on the FHIRCore app. At the moment the search only works  for the Patient Family name and given name 

```
{
  "resourceType": "Patient",
  "id": "969",
  "identifier": [ {
    "use": "official",
    "system": "http://who.int/ddcc/hcid",
    "value": "111000111"
  } ],
  "active": true,
  "name": [ {
    "family": "Murphy",
    "given": [ "Eddie" ]
  } ],
  "telecom": [ {
    "system": "phone",
    "value": "744585"
  } ],
  "gender": "male",
  "birthDate": "1986-09-19",
  "address": [ {
    "city": "Rome",
    "country": "Italy"
  } ]
}
```

**Comment by f-odhiambo** [comment]
> is this a UUID?
> 
> why is this required, what are the use cases?

When creating a resource directly on the HAPI FHIR it creates the resource with an incremented ID 001,002...etc i.e 

```
{
  "resourceType": "001",
  "id": "001",
```

When you create a resource on the app is created using a UUID 

```
{
  "resourceType": "2387-sd23232-n232",
  "id": "001",
```

For the Barcode will fetch that resource using an identifier in the resource  i.e. The Barcode ID will be retrieved/stored on the identifier.value filed 
```
{
  "resourceType": "Patient",
  "id": "969",
  "identifier": [ {
    "use": "official",
    "system": "http://who.int/ddcc/hcid",
    "value": "111000111"
  } ],
```

**Comment by pld** [comment]
is that a typo, is `resourceType` `Patient` in those examples?

it seems like `ID` is an internal ID since that is outside of the resource and we'd want to search by a specific `identifier`, we could have server and app always create a specific identifier or type UUID (or something else)

do we need to have an ID when we create a resource on device? if we push a resource without an ID to HAPI what happens? will it assign it an autoincremented ID

**Comment by pld** [comment]
Cool, yea so what I'm suggesting is we don't touch or use ID, we assume that's for internal HAPI use only.

We use an identifier for querying that we control creation of on both device and server, and we set this to be a UUID
