### ISSUE TITLE
Quest v0.2 / G6PD: Take a photo within a Questionnaire 

### ISSUE THREAD

**Issue by isabelcshaw** [opensrp/fhircore#620]
[**ONLY** address this issue if all other work in this milestone is complete or accounted for. It is more important to deliver a stable version of the rest of this milestone than to include this one feature in the delivery.] 

As part of the G6PD requirements, the user must submit an image of the test results that they have entered. 

_**As an end user, I want to be able to open the G6PD form, fill in the data fields, take a picture, and submit the form.**_ 

Requested solution: 
Determine how to properly capture an image within a questionnaire and add the supporting UI (as seen below). 

<img width="296" alt="Screen Shot 2021-10-11 at 1 39 49 PM" src="https://user-images.githubusercontent.com/12836913/136853012-ba73ffa8-bbdf-4038-99db-3f94ebb69d23.png">

**Comment by f-odhiambo** [comment]
@FikriMilano Check this out
<img width="755" alt="Screen Shot 2021-10-14 at 12 23 38 PM" src="https://user-images.githubusercontent.com/4540684/137289790-c58d1690-d580-491c-bebf-a3d2108a17a7.png">

**Comment by FikriMilano** [comment]
> 
> 
> @FikriMilano Check this out <img alt="Screen Shot 2021-10-14 at 12 23 38 PM" width="755" src="https://user-images.githubusercontent.com/4540684/137289790-c58d1690-d580-491c-bebf-a3d2108a17a7.png">

Thanks!

**Comment by f-odhiambo** [comment]
> Yeah I think that would be easier, thanks.
> 
> Also, I got this idea yesterday. So I plan to use `attachment` for this. Since there's no Attachment widget provided from the Android FHIR SDK. I think we can create a custom one for FHIRCore in the engine module. So that we can use it in other apps too.
> 
> We can create a `CustomQuestionnaireFragment` that inherits from `QuestionnaireFragment` which will override the `getCustomQuestionnaireItemViewHolderFactoryMatchers`. Then we can add the `CustomAttachmentFactory` in it by matching the `QuestionnaireItemType`.
> 
> FYI an example for attachment: http://build.fhir.org/ig/HL7/sdc/examples.html#using-mimetype-and-maxsize
> 
> @pld @f-odhiambo

@FikriMilano I think this is a nice idea to have this extensible to other apps and can be reusable, to which resource will the attachment be tagged to?

**Comment by FikriMilano** [comment]
> 
> @FikriMilano I think this is a nice idea to have this extensible to other apps and can be reusable, to which resource will the attachment be tagged to?

To display it, I think it should be part of Questionnaire.
When saving, it will be QuestionnaireResponse.

**Comment by pld** [comment]
What's the reason to store this, and what specifically would be stored, in the QuestionnaireResponse?

**Comment by FikriMilano** [comment]
@pld Because we need image reference when uploading one. It could be base64Binary and/or url.

It may store as follows but not limited to:

- contentType (required when there's data, optional when there's url - mimeType e.g. jpeg, png)

- data (optional - base64Binary)

- url (optional - url)

- title (optional - string)

And by using QuestionnaireResponse we can store it as an answer in valueAttachment.

For more info:
https://www.hl7.org/fhir/datatypes.html#Attachment
https://www.hl7.org/fhir/questionnaireresponse.html#resource

**Comment by pld** [comment]
Ah of course, that makes sense.

Could we embed the binary data directly in the QuestuonnaireResponse instead of involving another resource?

**Comment by FikriMilano** [comment]
@pld If by resource you mean Attachment, then yes.

Since the binary data will be base64 encoded, which is a string data type. We can store it in valueString.
Although the size will be limited to 1MB, we can still do it as long the image got compressed.
https://www.hl7.org/fhir/questionnaireresponse.html#resource
https://www.hl7.org/fhir/datatypes.html#string

We couldn't directly use base64Binary data type, because QuestionnaireResponse doesn't support that.
https://www.hl7.org/fhir/questionnaireresponse.html#resource
https://www.hl7.org/fhir/datatypes.html#base64Binary.

**Comment by FikriMilano** [comment]
@pld Also, I got this idea today.

We can just drop the idea of using Attachment and the use of QuestionnaireItemType itself for custom questionnaire widget.

Since it's custom, we can use an `extension` that has a specific `url` and `valueString` to match if it's a Photo Capture questionnaire widget or not.
The `url` may be the questionnaire widget documentation.

Should be something like this:
```
"item": [
  {
    "linkId": "1.1",
    "text": "Photo of device"
    "extension": [
      {
        "url": "http://doc-of-photo-capture",
        "valueString": "photo-capture"
      }
    ]
  }
]
```

As for the `valueString` that will be returned as QuestionnaireResponse, it can be handled inside the CustomPhotoCaptureFactory (the widget) itself.

The cool thing is, in the future we can create other custom questionnaire widgets the same way as that (with specific `url` and `valueString` as it's `extension`) and return any value as long it's supported by QuestionnaireResponse.
e.g. Location widget, VoiceRecorder widget, etc.

Since it's in the engine module, it can be easily reused across other apps too.

CC @f-odhiambo
