### ISSUE TITLE
Research effect of pre-processing images on MLKit digit capture

### ISSUE THREAD

**Issue by vincent-karuri** [opensrp/fhircore#69]
MLKit struggles with capturing 7-segment displays. As part of UW's input on this, we may want to breakdown the digit recognition process into 3-4 parts:

1. Create boxed ROIs around which we expect readings to be displayed on the screen (similar to fiducials in RDT) - _this is optional_
2. Pre-process image e.g. identify digit blobs, remove excess spacing between digits etc.
3. Send results from 2 to MLKit for recognition
4. Post-process results from MLKit based on contextual understanding from 1 - _also optional_

2 can be simulated manually by using say a marker pen to convert the "broken" digits into solid blobs and seeing how this performs on MLKit. Editing software could also be used to do this and to reduce spacing between digits etc.

Ongoing research is documented [here](https://docs.google.com/document/d/1JwAfdeFDncYXbymO-hHktWZSOnMqYSHwmDktxFVV5Dc/edit).

**Comment by shoaibmushtaq25** [comment]
I tested the Google ML Kit scanning after some manual painting and black and white filters on the images of Standard G6PD device screen readings. The results are improving to some extent after applying these manual edits on the images but not 100% accurate. Still ML Kit is not able to recognize some of the digits. The results scans are attached in the attached document [here](https://docs.google.com/document/d/1JwAfdeFDncYXbymO-hHktWZSOnMqYSHwmDktxFVV5Dc/edit)

**Comment by shoaibmushtaq25** [comment]
**Observations with Anyline Samples**
I also came across a different platform while searching for seven segment display readings.
This is https://anyline.com/. And also tried their sample/ demo apps built for Analog/digital meter readings and the demo app can recognize the seven segment display correctly. Attaching some screen shots here as well.
Also I read through the anyline portfolio and came to know that they have built a custom solution in the past for a company mySugar in order to log the sugar level readings after scanning the Glucomoter (device to check the sugar level). 
Below is the link to that story around "mySugar" 
https://anyline.com/success-stories/mysugr-improves-diabetes-therapy-mobile-scanni[…]p&utm_campaign=b2b_leads_global_prospects_success-story-ocr-app
Thoughts: Looks like their solutions are paid, so I didn't pursue in that direction too much. 
Thanks @f-odhiambo for the follow up that with Anyline team and we will have a call scheduled with Anyline representatives on 13 April at 10:45 Am (EAT).

**Comment by shoaibmushtaq25** [comment]
**Some updates on G6PD from UW**
I found an interesting open source project that reads seven-segment digits using tesseract.
https://github.com/arturaugusto/display_ocr
They released their own tesseract model that was trained to read seven-segment digits better. And, in their code, they use opencv's erode function which fills in the gap between each segment (https://github.com/arturaugusto/display_ocr/blob/master/py3_raspberry_pi.py#L105). Although their code is implemented with python, I think it can easily be translated into java, since both tesseract and opencv support java/android.
Maybe your team can try this project whether this works or not. If it works, then it could worth try to port it to java/android.
Best,
CJ

**Comment by shoaibmushtaq25** [comment]
I am struggling to try this project (https://github.com/arturaugusto/display_ocr) suggested by University of Washington guys. I tried to run and test it but not sure exactly that how can we test our scenario with it as I am not expert on python as well. I would appreciate any help on that or anyone from the team can try it on their end to check if it works with our use case or not.

**Comment by vincent-karuri** [comment]
@shoaibmushtaq25 I think you'd mentioned there were some errors when trying to run it. Could you please elaborate on those?

Were you trying to deploy the app? If so, how did you go about it?

**Comment by shoaibmushtaq25** [comment]
Actually, When I run the python project with the Input Image Path (Image of G6PD device). It opens an Image and some controllers to control threshold, erode and Filter as shown in the picture below. But when I try to select the ROI (Region of interest) to apply , the project crashes. I will add the video around it here as well.
![Screenshot from 2021-04-12 17-52-32](https://user-images.githubusercontent.com/12672919/114397640-535fb100-9bb8-11eb-8f3d-c5a4d55de823.png)

**Comment by vincent-karuri** [comment]
What is the error output that is showing on the terminal?

**Comment by shoaibmushtaq25** [comment]
> What is the error output that is showing on the terminal?
Here is the error output showing on the terminal..
![Screenshot from 2021-04-13 13-58-05](https://user-images.githubusercontent.com/12672919/114526402-6332d000-9c60-11eb-93d2-f1e43b065ced.png)

**Comment by vincent-karuri** [comment]
findings here are documented in the document in the issue description https://github.com/opensrp/fhircore/issues/69#issue-851439300
