### ISSUE TITLE
Quest v0.2 / G6PD : Add multi language support in Quest 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#796]
**Is your feature request related to a problem? Please describe.**
Add MultiLanguage support item to the setting page of the Quest  to switch  from either 
1. English
2. Swahili

**Describe the solution you'd like**
Add updated questionnaire with both English and Swahili translations 

**Describe alternatives you've considered**
N/A

**Additional context**
<img src="https://user-images.githubusercontent.com/4540684/143269769-3cd3d61a-e1a2-4ac7-bbaf-e187964c8487.png" width="200" height="400" />

**Comment by pld** [comment]
For this the set of supported languages must be configuration based, not hard coded

**Comment by ellykits** [comment]
> For this the set of supported languages must be configuration based, not hard coded

Noted. We have a language config property in [ApplicationConfiguration](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/app/ApplicationConfiguration.kt)

**Comment by pld** [comment]
Cool, I guess we can set that with a list supplied by a synced FHIR resource

**Comment by ellykits** [comment]
**Proposal**

I think we can move the `switchLanguages` configuration from the `RegisterViewConfiguration` to `ApplicationConfiguration`. It is an application level config and should only be set from one place for the entire application. **It may not be necessary actually** since we can count the number of languages provided in the `languages` of `ApplicationConfiguration` and update the logic in the following manner:

- **If** we have multiple languages provided in the `ApplicationConfiguration` then language switcher is activated
- **Else** inactivate the language switcher (only one language available in the `languages` config)

**NOTE**: 
1. `switchLanguages` is used in the side menu implemented `BaseRegisterActivity` (needs to be refactored)
2. The `PATIENT_REGISTER` is no longer needed in [AppConfigClassification](https://github.com/opensrp/fhircore/blob/issue-796-multi-lang-support/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/AppConfigClassification.kt) (By default only `Login` and `Application` config classifications are common the registers can be named differently for different apps)
