### ISSUE TITLE
Add Composition & All linked Resources fetch & download functionality. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#809]
**Description of feature**
- The Composition resource will have a link to other resources that the dynamic app configurations
- This will be a 2 point process
    - Download the initial composition resource 
    - Download all the resources linked in the composition resource. 
- [Composition resource](https://github.com/opensrp/fhircore/discussions/594#discussioncomment-1635591) usage documentation. 

**Describe the enhancement**
- [x] Download the Composition resource. The id to identify the resource to download will be from the app settings. 
     - [ ] The composition id is under the `composition_id` key in the settings table.
- [x] From the Composition resource `section` attribute download all the resources referenced. 
     - [ ] Also mark these resources as synced in the `SyncedResourceEntity` table (To be discussed, the assumption here is this table is used during sync)
- [ ] Download the referenced resources on the composition `author` and `custodian`

**Acceptance criteria**
- [x] Composition resource should be generated first.
- [x] The resources should be assigned the correct ids

**This issue depends on the following issues.** 
[Add a composition input on the settings page](https://github.com/opensrp/fhircore/issues/769 )
[Design & create the SettingsEntity table & BinaryEntity table in the SQlite DB](https://github.com/opensrp/fhircore/issues/821)

**Comment by pld** [comment]
Feels like we might want to bundle up all the resources into a single file before we send it to the device?

**Comment by dubdabasoduba** [comment]
> Feels like we might want to bundle up all the resources into a single file before we send it to the device?

@pld Are thinking of bundling this up on the server in a bundle? If so I can try to see if the whole bundle can be fetched using the `_include` FHIR search parameter.

**Comment by pld** [comment]
Cool yea I haven't thought about it deeply, but was thinking of it server side, since from use-cases we've seen we know that slow first syncs have been a problem historically so if there's a way for us to speed that up it's worth having that option, can also be something we do later.

If we used the Bundle resource instead of Composition does that change anything?

**Comment by dubdabasoduba** [comment]
> Cool yea I haven't thought about it deeply, but was thinking of it server-side, since from use-cases we've seen we know that slow first syncs have been a problem historically so if there's a way for us to speed that up it's worth having that option, can also be something we do later.
> 
> If we used the Bundle resource instead of Composition does that change anything?

It will help reduce the fetch queries for the required resources. It however makes the response quite big because of the content targeted resources we might end up having. I am also not sure how it handles binaries (if we end up using them). The Binary resource URL automatically triggers a download of the Binary uploaded.

**Comment by pld** [comment]
Hmm k so requires more R&D, cool we don't need to commit to anything here

**Comment by f-odhiambo** [comment]
Kindly note that @maimoonak will pause work on this to work on #1033.

Critical fix @dubdabasoduba

**Comment by dubdabasoduba** [comment]
@f-odhiambo I am okay with this. Please update me incase anything changes

**Comment by maimoonak** [comment]
The work was done #1091  with Binary resource and needs to be updated with Parameters resource instead of Binary.

The parameters Resource https://hl7.org/fhir/parameters.html, by definition, can only be used as embedded resource and not as a reference. The definition of this in spec states that the resource is just for passing info between components and can not be entitled to be persisted. So either we would have to skip Parameters OR replace Composition with some resource that allows embedded resources
Currently it is persisting due to the reason that these are inheriting resource. However, in future FHIR can take any decision.. either update their doc and make it persistable and a normal resource by definition as all others, OR they can move it to some other category and remove the current rest endpoint... HAPI is implementing this contrary to FHIR specs..

@f-odhiambo @dubdabasoduba . Shall I proceed and change current impl to Parameters

**Comment by f-odhiambo** [comment]
I am of the opinion composition resource still give more room to allow for configurability over Parameters resources. 
Any thoughts on this approach @pld?

**Comment by pld** [comment]
Why can't we embed the Parameter resource in a Composition? Is there another appropriate resource we can embed a Parameter resource in, and then have Composition refer to that other resource?

**Comment by maimoonak** [comment]
https://hl7.org/fhir/composition.html No field in composition has room to hold a Resource data.

**Comment by pld** [comment]
Got it, reference not embedding, @maimoonak let's move forward w/Binary for now, while we see what the better way is to get these in to structured resources

**Comment by maimoonak** [comment]
The issue is final all done, tested, and PR is ready to review #1091 . There are alot of files changes but most of those are in tests.

The composition resource structure looks like [this](https://github.com/opensrp/fhircore/blob/809_config_comp/android/quest/src/test/resources/configs/g6pd/config_composition.json) . [REst of the resources ](https://github.com/opensrp/fhircore/blob/809_config_comp/android/quest/src/test/resources/configs/g6pd)are same as assets files wrapped into Binary . [Sync config](https://github.com/opensrp/fhircore/blob/809_config_comp/android/quest/src/test/resources/configs/g6pd/config_sync.json) is Parameters and is FHIR entity wrapped into Binary. There is room to chnage implementation to use other resource inplace of Binary in future.

Composition.identifier.value=application id
Composition..section.focus.identifier=workflow name

see the transformation [here](https://github.com/opensrp/fhircore/blob/809_config_comp/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt#L83)

@dubdabasoduba @pld Kindly review PR and the implementation
