### ISSUE TITLE
Fix choice question

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#88]
The gender question authored as a choice question has a bug related to the **SDC** implementation and **ResourceMapper**. 

1. SDC does not place the selected `choice.code` in the `QuestionnaireResponseItem.answer`. The answers are available inside the `QuestionnaireResponseItem.item[0].answer`
2. `ResourceMappper` expects the `QuestionnaireResponseItem` to either have the `answer` or `initial` properties. The `ResourceMapper` also expects the answer to be of the defined model while SDC coerces the answer of a `choice` question to `Coding` model always. This will always cause an error since the `ResourceMapper` does not allow extracting the `code` from the `Coding` object and SDC does not allow any other types to be defined as options or initial values

**Comment by syedowaisali90** [comment]
Hi @ekigamba Currently, I don't have a quite knowledge of SDC and I'm a bit confused about the detail. So, is it something about the patient-registration-form `gender` related issue which is currently showing as a text field instead of `radio-button`, and if not so could give me some more ground about the issue. It would be very helpful to me. 
Thanks

**Comment by ekigamba** [comment]
@syedowaisali90 This was fixed. I apologise for leaving this open. This was fixed in this PR https://github.com/google/android-fhir/pull/326 which is still open.

There were two problems:
1. The questionnaire was not authored correctly
2. `ResourceMapper` did not support the Coding model returned for choice questions


I am going to close this question
