### ISSUE TITLE
Quest v0.2 / G6PD : Determine recommended malaria treatment based on patient classification and add a Medication/MedicationRequest

### ISSUE THREAD

**Issue by mwkhan1983** [opensrp/fhircore#945]
**Is your feature request related to a problem? Please describe.**
As a G6PD app user, I would like to view the recommended malaria treatment for a patient post-evaluation based on a CQL expression

**Describe the solution you'd like**
- Please refer to the image below for threshold values for recommended treatment
- Recommended treatment logic against patient classification is to be stored within the CQL lib. 
- Anyone with 16 yrs and above to receive the regimen and not lower.
- If haemoglobin reading is under or equal to 8 g/dl, PQ is not given
- Implementation of the mock design (regimen part on the test results page) to allow the user to view recommended treatment

**Describe alternatives you've considered**
- Edit the current CQL expression to be able to define Medication and MedicationRequest for the patient and generate the appropriate resources 

**Additional context**
![456](https://user-images.githubusercontent.com/69383347/149340339-10a723d2-707f-4ef8-b18e-ffc638c21ed7.png)

<img width="299" alt="123" src="https://user-images.githubusercontent.com/4540684/150127782-7f2b7611-42cf-4fc0-be72-0d089636924f.png">

**Acceptance Criteria**
- [ ] View recommended regimen as defined in the CQL statement 

**Linked Issues**
1. #779
2. #781

**Comment by f-odhiambo** [comment]
@maimoonak Based on the latest APK shared quest-debug-20220220.apk kindly add a check to endure that all the status messages and also the regimen are recorded for all categories i.e. Normal, Deficient and Intermediate.  Not seeing results for deficient 

<img src="https://user-images.githubusercontent.com/4540684/150292404-992ddd93-8ec6-4c48-80d6-55c7c624407b.png" width="200" height="400" />

**Comment by maimoonak** [comment]
@f-odhiambo the regimen is not given if HB is <= 8 OR patient is under <= 16yrs. Please make HB 9+ and ensure patient is 16+

**Comment by f-odhiambo** [comment]
Cool sounds good. Thanks for the feedback. Will continue further testing

**Comment by maimoonak** [comment]
Missing value now looks like this... this might show on some older records as well where data was missing during development
<img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/150308380-9ee3f1c9-c2a9-4ac2-b902-db2e208f8498.jpg"/>

**Comment by f-odhiambo** [comment]
@maimoonak Do we have a PR linked to this issue?

**Comment by maimoonak** [comment]
PR is linked above #969 . 

Notable points:

- MedicationRequest entity is as follows
`
{ "resourceType":"MedicationRequest", "status":"active", "intent":"proposal", "subject":{ "reference":"Patient/P1" }, "encounter":{ "reference":"Encounter/E1" }, "authoredOn":"#NOW", "category":[ { "coding":[ { "system":"http://snomed.info/sct", "code":"86859003", "display":"Glucose-6-phosphatedehydrogenasedeficiencyanaemia" } ] } ], "medicationCodeableConcept":{ "coding":[ { "system":"http://snomed.info/sct", "code":"429663004", "display":"Primaquine(substance)" } ] }, "dosageInstruction":[ { "timing":{ "repeat":{ "frequency":1, "period":8.0, "periodUnit":"wk" } }, "route":{"coding":[{"system":"http://snomed.info/sct","code":"26643006","display":"Oraluse"}]}, "doseAndRate":[ { "type":{ "coding":[ { "system":"http://terminology.hl7.org/CodeSystem/dose-rate-type", "code":"ordered", "display":"Ordered" } ] }, "doseQuantity":{ "value":0.75, "unit":"mg/kg", "system":"http://unitsofmeasure.org" } } ] } ] }
`

**Differences from original shared entity**
- reasonCode -> category used instead as reasonCode is not searchable
- basedOn -> diagnosticReport can not be linked as it is not supported by [MedicationRequest](https://hl7.org/fhir/medicationrequest.html)
- medication -> is CodeableConcept instead of Medication Reference. Entities do not support internal references as uuid generation is not possible within CQL
- dosageInstruction -> text not added as it is not needed and has repeating info
- route -> Display name is different and is picked from[ FHIR doc ](https://hl7.org/fhir/valueset-route-codes.html) instead

Notable changes
- Updated cql evaluator version to support `Now`. engine to 'org.opencds.cqf.cql:engine:1.5.4-SNAPSHOT' from 1.5.2, 'org.opencds.cqf.cql:evaluator.builder:1.3.1-SNAPSHOT' from 1.2.1
- Some custom handling of Dosage entity was required to handle FHIR evaluator bug (https://github.com/DBCG/cql_engine/issues/537) 
- PQMedication added as separate Library and added support to run multiple Libraries for same Questionnaire
- Library sync changed to id based sync to omit out unnecessary Libs
