### ISSUE TITLE
Quest - reduce time it takes to sync resources on load

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#949]
**Name of feature to enhance**
Sync optimization for the Quest application 

**Usecase/scenario** 
How can we optimize the sync process to be able to make it work more efficiently and leverage publisher fields on resources and configs on the quest app to reduce the amount of time needed to sync resources from HAPI or sync on-demand only resources that match the config parameters? 

**Description of feature**
implement a mechanism that allows the current sync operation to be as optimized as possible for optimal peek performance 

**Describe the enhancement**
- [x] Research and development  on a sync optimization strategy 
- [x] Document findings with their pros and cons 
- [x] Have a discussion to decide on the best approach  that best addresses the sync issues 
- [x] Add issues addressing how to go about the enhancements on the Sync feature

**Comment by f-odhiambo** [comment]
@FikriMilano Kindly take note that the initial ticket has been reassigned due to duplication . 

Also note, If new enhancements on FHIR Engine is required document them here https://github.com/google/android-fhir/issues/1099**

**Comment by FikriMilano** [comment]
@f-odhiambo so there are 2 possible ways that could be possible to optimize this:

1. Based on this Room DB benchmark, it shouldn't take too long to insert the resources into the database. So it doesn't make sense for the sync to take around 7 minutes (on my case). Therefore, perhaps we can improve the FHIR Engine, but haven't found a way to do it.
Benchmark test reference: https://medium.com/swlh/android-dbms-performance-comparison-using-the-jetpack-benchmark-library-19581bf67443
3. Have a priority initial sync, that basically only sync the necessary resource for the app to be up and running. And then do another sync in the background to fully sync the rest of the resource. But before doing a full sync, some of the features may won't work properly because of missing resources e.g. patient searching will be limited to the patients that have been sync.

**Comment by maimoonak** [comment]
1 - During sync fhir-engine saves resources, and then foreach indexed/searcheable field adds an index entry based on index type into other tables. see [ResourceIndexer](https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt#L258) class. This might be leading to increased time as one resource in database can lead upto 3-7 entries into other tables.
2 - For now we do not allow app be ready or usable unless data is setup properly. @f-odhiambo can give a final verdict on this, but it depends on field usage. Shall we allow HW to roam around app without sync complete. This can lead to duplicate entries as well incase of sync in progress and app in  use by HW.
3 - In past with opensrp we faced this issue where we were dealing 50K+ records which was not possible to sync via regular sync method. We actually ended up with a solution where we prepare sqlite DB on server side, and then imported all data via simple inserts into our DB which made it super fast. The prep of sqlite on server posed its own challenges but it solved our main problem. @f-odhiambo @FikriMilano I guess we should discuss this issue over call and then add relevant members for further discussions

**Comment by dubdabasoduba** [comment]
> 1 - During sync fhir-engine saves resources, and then foreach indexed/searcheable field adds an index entry based on index type into other tables. see [ResourceIndexer](https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt#L258) class. This might be leading to increased time as one resource in database can lead upto 3-7 entries into other tables. 2 - For now we do not allow app be ready or usable unless data is setup properly. @f-odhiambo can give a final verdict on this, but it depends on field usage. Shall we allow HW to roam around app without sync complete. This can lead to duplicate entries as well incase of sync in progress and app in use by HW. 3 - In past with opensrp we faced this issue where we were dealing 50K+ records which was not possible to sync via regular sync method. We actually ended up with a solution where we prepare sqlite DB on server side, and then imported all data via simple inserts into our DB which made it super fast. The prep of sqlite on server posed its own challenges but it solved our main problem. @f-odhiambo @FikriMilano I guess we should discuss this issue over call and then add relevant members for further discussions

@maimoonak Option 3 is interesting I would like to understand more about it. Option 2 might be hard since for the app to be used in a fully offline mode we need to sync everything

**Comment by FikriMilano** [comment]
Thanks for the input @maimoonak 

Option 3 is really awesome, personally I like the idea to use this since it fixes the problem, but I don't think I have the final say on whether to use this or the Sync API.
What do you think @ekigamba?

@dubdabasoduba if that's the case, we can forgo option 2

**Comment by ekigamba** [comment]
I also agree that option 3 sounds interesting given that it will solve the potential problem of resource indexing causing sync to be slow.

I think we initially need to understand which part of sync is slow and then we can optimize that. I understand that we currently sync all the resources, this will not mirror our initial production case since we expect location mapping and other filters to reduce the number or resources per initial/sequential sync. Additionally, we do not expect to share servers across multiple apps.

I agree that using the publisher filters will significantly reduce the sync time for questionnaires(and other relevant resources) on our multi-tenant setup. For WFP-CODA, we solved this by tagging each resource with the app-id and providing this filter for sync because the filter it is natively supported by server, client and can be used across all resources. [See more here](https://github.com/onaio/fhircore-mirror/pull/34/files)

From our previous investigations on the WFP-CODA project, the parsing of string to a FHIR resource and/or encoding FHIR resource to string consumes a lot of resources(memory and CPU time). This took 8 seconds on the slow device.

**Comment by pld** [comment]
Let's start by filtering, I'd think we want that for reasons other than performance so the user only downloads data they should have access to

**Comment by FikriMilano** [comment]
@pld @ekigamba 
I think FHIRCore already has a sync based on publisher and organization filters to reduce the resource, but it still takes too long.

So, I will add more filters such as:
- Patients based on 'address-country'
- Encounter based on 'location'
etc.

And see how much improvement that would bring.

**Comment by pld** [comment]
I'm not sure those are the correct filters based on our use cases. Please don't work on that until you've discussed with Ben M

**Comment by FikriMilano** [comment]
Okay
cc @dubdabasoduba

**Comment by FikriMilano** [comment]
>3 - In past with opensrp we faced this issue where we were dealing 50K+ records which was not possible to sync via regular sync method. We actually ended up with a solution where we prepare sqlite DB on server side, and then imported all data via simple inserts into our DB which made it super fast. The prep of sqlite on server posed its own challenges but it solved our main problem. 
@maimoonak 

@pld what do you think about option 3?

**Comment by ekigamba** [comment]
> @pld @ekigamba I think FHIRCore already has a sync based on publisher and organization filters to reduce the resource, but it still takes too long.
> 
> So, I will add more filters such as:
> 
> * Patients based on 'address-country'
> * Encounter based on 'location.address-country'
>   etc.
> 
> And see how much improvement that would bring.

Which resources can these filters be added to?

**Comment by FikriMilano** [comment]
> I think 3 could makes sense longer term but is too heavy a lift until we've taken out some lower hanging fruit. Can we turn that into a separate issue and leave in the "icebox" for the time being?

Sure

**Comment by FikriMilano** [comment]
@dubdabasoduba yeah, those 2 are enabled
https://github.com/opensrp/fhircore/blob/main/android/anc/src/main/assets/configurations/app/sync_config.json

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba yeah, those 2 are enabled https://github.com/opensrp/fhircore/blob/main/android/anc/src/main/assets/configurations/app/sync_config.json

@FikriMilano @maimoonak do we need any other configuration for these to work?

**Comment by FikriMilano** [comment]
@dubdabasoduba not really, that's the only config that we need

**Comment by maimoonak** [comment]
@FikriMilano @dubdabasoduba If we are looking into loading data faster for now, ee can change the organization of demo user to remove the data association from current app (would need some sample data entry to ensure app has some data and looks good). This way the time of sync would be reduced. But this is not a solution of sync problem. We can also remove Binary resources sync from app to make it a little more faster.

**Comment by FikriMilano** [comment]
I just had a call this morning w @maimoonak 
The conclusion is to increase the `_count` parameter which will increase the total records retrieved per API call.
I updated the QuestConfigService and test it.

Here's the result (Quest app - emulator):
| Total Sync Duration| Count limit per API call| Size per API call|
| ------------- | ------------- | ------------- |
| 7 min 30 sec  | 20 (Now/default)  | ~30 KB |
| 4 min 13 sec  | 40  | ~60 KB |
| 2 min 21 sec  | 60  | ~90 KB |

**Comment by pld** [comment]
Great, good catch, what happens if we increase it even further?

**Comment by dubdabasoduba** [comment]
> I just had a call this morning w @maimoonak The conclusion is to increase the `_count` parameter which will increase the total records retrieved per API call. I updated the QuestConfigService and test it.
> 
> Here's the result (Quest app - emulator):
> 
> Total Sync Duration	Count limit per API call	Size per API call
> 7 min 30 sec	20 (Now/default)	~30 KB
> 4 min 13 sec	40	~60 KB
> 2 min 21 sec	60	~90 KB

What's the max acceptable size per API call. I think that can guide us on the count limit to use.

**Comment by FikriMilano** [comment]
@pld @dubdabasoduba
So the previous test result is not fully correct, because there's a timeout exception which I missed.
I increased the timeout limit then ran some test again and the result is:
Here's the result (Quest app - emulator):
| Total Sync Duration| Count limit per API call| Size per API call|
| ------------- | ------------- | ------------- |
| 7 min 30 sec  | 20 (Now/default)  | ~30 KB |
| 4 min 16 sec  | 40  | ~60 KB |
| 4 min 06 sec  | 60  | ~90 KB |
| 3 min 55 sec  | 100 | ~150 KB |
| 3 min 53 sec  | 200 | ~300 KB (In theory, some resource doesn't have this much record) |

**Comment by FikriMilano** [comment]
> Great, good catch, what happens if we increase it even further?

@pld we can, but the result is capped at ~3 min 55 sec

**Comment by FikriMilano** [comment]
> What's the max acceptable size per API call. I think that can guide us on the count limit to use.

@dubdabasoduba based on the latest test result, 100 should be the right balance

**Comment by dubdabasoduba** [comment]
> > What's the max acceptable size per API call. I think that can guide us on the count limit to use.
> 
> @dubdabasoduba based on the latest test result, 100 should be the right balance

I think I am okay with the 100 `_count`.

**Comment by FikriMilano** [comment]
@f-odhiambo  @dubdabasoduba
We need to refactor the QuestConfigService so that it can process multiple parameters.
Also to increase the timeout limit to 2 minutes as well, because of the bulky sync.

Files to be changed:
- sync_config
- QuestConfigService
- NetworkModule
- ConfigurationRegistry

**Comment by f-odhiambo** [comment]
Closed via PR #1128

**Comment by dubdabasoduba** [comment]
@FikriMilano Please post the new sync times on this issue after the count fix.
